sonar.projectKey=week-8-rag
sonar.projectName=week-8 RAG PDF
sonar.projectVersion=1.0

sonar.sources=app,ingestor.py,query.py
sonar.inclusions=app/**/*.py,ingestor.py,query.py

sonar.exclusions=.venv/**,__pycache__/**,docs/**,.github/**,.scannerwork/**,uv.lock

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
